### ISSUE TITLE
TUTORIAL

### ISSUE THREAD

**Issue by Amustache** [CLICGameStarProjects/NiceLAN#13]
Du coup l'objectif c'est d'arriver à cet écran :

![image](https://user-images.githubusercontent.com/5108539/201542006-f72345fa-c615-432d-907d-63f7e93fba91.png)

N'hésitez pas si vous avez besoin d'aide !

**Comment by Astraval** [comment]
![image](https://user-images.githubusercontent.com/91798381/203663638-4883199b-3333-4eb3-a26b-386e6345662e.png)
De même :)
